/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NinjaExtraAPI
 * OpenAPI spec version: 1.0.0
 */
/**
 * 账户信息输出
 */
export interface AccountOutSchema {
  date_joined: string;
  email: string;
  is_active: boolean;
  username: string;
}

export type BookCreateInSchemaAttributes = { [key: string]: unknown };

export type BookCreateInSchemaCategoryId = number | null;

/**
 * 创建书籍时的输入
 */
export interface BookCreateInSchema {
  attributes?: BookCreateInSchemaAttributes;
  category_id?: BookCreateInSchemaCategoryId;
  description?: string;
  title: string;
}

export type BookOutSchemaAttributes = { [key: string]: unknown };

export type BookOutSchemaCategoryId = number | null;

/**
 * 完整书籍的输出
 */
export interface BookOutSchema {
  attributes: BookOutSchemaAttributes;
  category_id?: BookOutSchemaCategoryId;
  cover_image_path: string;
  create_time: string;
  description: string;
  id: number;
  status: string;
  title: string;
  update_time: string;
}

export type BookUpdateInSchemaAttributesAnyOf = { [key: string]: unknown };

export type BookUpdateInSchemaAttributes = BookUpdateInSchemaAttributesAnyOf | null;

export type BookUpdateInSchemaCategoryId = number | null;

export type BookUpdateInSchemaDescription = string | null;

export type BookUpdateInSchemaTitle = string | null;

/**
 * 更新书籍时的输入
 */
export interface BookUpdateInSchema {
  attributes?: BookUpdateInSchemaAttributes;
  category_id?: BookUpdateInSchemaCategoryId;
  description?: BookUpdateInSchemaDescription;
  title?: BookUpdateInSchemaTitle;
}

export type ChapterCreateInSchemaContentItem = { [key: string]: unknown };

/**
 * 创建章节时的输入
 */
export interface ChapterCreateInSchema {
  chapter_number: number;
  content?: ChapterCreateInSchemaContentItem[];
  title: string;
}

export type ChapterOutSchemaContentItem = { [key: string]: unknown };

/**
 * 完整章节的输出
 */
export interface ChapterOutSchema {
  book_id: number;
  chapter_number: number;
  content: ChapterOutSchemaContentItem[];
  create_time: string;
  id: number;
  status: string;
  title: string;
  update_time: string;
}

export type ChapterUpdateInSchemaChapterNumber = number | null;

export type ChapterUpdateInSchemaContentAnyOfItem = { [key: string]: unknown };

export type ChapterUpdateInSchemaContent = ChapterUpdateInSchemaContentAnyOfItem[] | null;

export type ChapterUpdateInSchemaStatus = string | null;

export type ChapterUpdateInSchemaTitle = string | null;

/**
 * 更新章节时的输入
 */
export interface ChapterUpdateInSchema {
  chapter_number?: ChapterUpdateInSchemaChapterNumber;
  content?: ChapterUpdateInSchemaContent;
  status?: ChapterUpdateInSchemaStatus;
  title?: ChapterUpdateInSchemaTitle;
}

/**
 * 邮箱验证时输入
 */
export interface EmailRequestInSchema {
  email: string;
}

/**
 * 错误字段
 */
export type ErrorDetailSchemaField = string | null;

/**
 * 错误详情
 */
export interface ErrorDetailSchema {
  /** 错误字段 */
  field?: ErrorDetailSchemaField;
  /** 错误信息 */
  message: string;
}

/**
 * JWT 输出
 */
export interface JwtOutSchema {
  access: string;
  refresh: string;
}

/**
 * 登录账户时输入
 */
export interface LoginInSchema {
  password: string;
  username: string;
}

/**
 * 响应数据
 */
export type OutSchemaAccountOutSchemaData = AccountOutSchema | null;

/**
 * 错误详情
 */
export type OutSchemaAccountOutSchemaErrors = ErrorDetailSchema[] | null;

export interface OutSchemaAccountOutSchema {
  /** 响应数据 */
  data?: OutSchemaAccountOutSchemaData;
  /** 错误详情 */
  errors?: OutSchemaAccountOutSchemaErrors;
  /** 消息 */
  message?: string;
  /** 时间戳 */
  timestamp?: string;
}

/**
 * 响应数据
 */
export type OutSchemaBookOutSchemaData = BookOutSchema | null;

/**
 * 错误详情
 */
export type OutSchemaBookOutSchemaErrors = ErrorDetailSchema[] | null;

export interface OutSchemaBookOutSchema {
  /** 响应数据 */
  data?: OutSchemaBookOutSchemaData;
  /** 错误详情 */
  errors?: OutSchemaBookOutSchemaErrors;
  /** 消息 */
  message?: string;
  /** 时间戳 */
  timestamp?: string;
}

/**
 * 响应数据
 */
export type OutSchemaChapterOutSchemaData = ChapterOutSchema | null;

/**
 * 错误详情
 */
export type OutSchemaChapterOutSchemaErrors = ErrorDetailSchema[] | null;

export interface OutSchemaChapterOutSchema {
  /** 响应数据 */
  data?: OutSchemaChapterOutSchemaData;
  /** 错误详情 */
  errors?: OutSchemaChapterOutSchemaErrors;
  /** 消息 */
  message?: string;
  /** 时间戳 */
  timestamp?: string;
}

/**
 * 响应数据
 */
export type OutSchemaJwtOutSchemaData = JwtOutSchema | null;

/**
 * 错误详情
 */
export type OutSchemaJwtOutSchemaErrors = ErrorDetailSchema[] | null;

export interface OutSchemaJwtOutSchema {
  /** 响应数据 */
  data?: OutSchemaJwtOutSchemaData;
  /** 错误详情 */
  errors?: OutSchemaJwtOutSchemaErrors;
  /** 消息 */
  message?: string;
  /** 时间戳 */
  timestamp?: string;
}

/**
 * 响应数据
 */
export type OutSchemaListBookOutSchemaData = BookOutSchema[] | null;

/**
 * 错误详情
 */
export type OutSchemaListBookOutSchemaErrors = ErrorDetailSchema[] | null;

export interface OutSchemaListBookOutSchema {
  /** 响应数据 */
  data?: OutSchemaListBookOutSchemaData;
  /** 错误详情 */
  errors?: OutSchemaListBookOutSchemaErrors;
  /** 消息 */
  message?: string;
  /** 时间戳 */
  timestamp?: string;
}

/**
 * 响应数据
 */
export type OutSchemaListChapterOutSchemaData = ChapterOutSchema[] | null;

/**
 * 错误详情
 */
export type OutSchemaListChapterOutSchemaErrors = ErrorDetailSchema[] | null;

export interface OutSchemaListChapterOutSchema {
  /** 响应数据 */
  data?: OutSchemaListChapterOutSchemaData;
  /** 错误详情 */
  errors?: OutSchemaListChapterOutSchemaErrors;
  /** 消息 */
  message?: string;
  /** 时间戳 */
  timestamp?: string;
}

/**
 * 错误详情
 */
export type OutSchemaNoneTypeErrors = ErrorDetailSchema[] | null;

export interface OutSchemaNoneType {
  /** 响应数据 */
  data?: null;
  /** 错误详情 */
  errors?: OutSchemaNoneTypeErrors;
  /** 消息 */
  message?: string;
  /** 时间戳 */
  timestamp?: string;
}

/**
 * 响应数据
 */
export type OutSchemaStrData = string | null;

/**
 * 错误详情
 */
export type OutSchemaStrErrors = ErrorDetailSchema[] | null;

export interface OutSchemaStr {
  /** 响应数据 */
  data?: OutSchemaStrData;
  /** 错误详情 */
  errors?: OutSchemaStrErrors;
  /** 消息 */
  message?: string;
  /** 时间戳 */
  timestamp?: string;
}

/**
 * 确认重置密码时输入
 */
export interface PasswordResetConfirmInSchema {
  password: string;
  password_confirm: string;
}

/**
 * 注册账户时输入
 */
export interface RegisterInSchema {
  email: string;
  password: string;
  password_confirm: string;
  username: string;
}

export type BookEndpointsGetBooksParams = {
  page?: number;
  page_size?: number;
  category_id?: number | null;
  status?: string | null;
};

export type BookEndpointsGetChaptersParams = {
  page?: number;
  page_size?: number;
};

export type BookEndpointsUploadCoverImageBody = {
  cover_image?: Blob;
};

/**
 * 请求验证账户
 * @summary 请求验证账户
 */
export type accountEndpointsAccountVerifyRequestResponse201 = {
  data: OutSchemaStr;
  status: 201;
};

export type accountEndpointsAccountVerifyRequestResponseSuccess = accountEndpointsAccountVerifyRequestResponse201 & {
  headers: Headers;
};
export type accountEndpointsAccountVerifyRequestResponse = accountEndpointsAccountVerifyRequestResponseSuccess;

export const getAccountEndpointsAccountVerifyRequestUrl = () => {
  return `/api/account-verifications`;
};

export const accountEndpointsAccountVerifyRequest = async (emailRequestInSchema: EmailRequestInSchema, options?: RequestInit): Promise<accountEndpointsAccountVerifyRequestResponse> => {
  const res = await fetch(getAccountEndpointsAccountVerifyRequestUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(emailRequestInSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountEndpointsAccountVerifyRequestResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountEndpointsAccountVerifyRequestResponse;
};

/**
 * 使用令牌验证账户
 * @summary 使用令牌验证账户
 */
export type accountEndpointsAccountVerifyConfirmResponse200 = {
  data: OutSchemaAccountOutSchema;
  status: 200;
};

export type accountEndpointsAccountVerifyConfirmResponseSuccess = accountEndpointsAccountVerifyConfirmResponse200 & {
  headers: Headers;
};
export type accountEndpointsAccountVerifyConfirmResponse = accountEndpointsAccountVerifyConfirmResponseSuccess;

export const getAccountEndpointsAccountVerifyConfirmUrl = (uidb64: string, token: string) => {
  return `/api/account-verifications/${uidb64}/${token}`;
};

export const accountEndpointsAccountVerifyConfirm = async (uidb64: string, token: string, options?: RequestInit): Promise<accountEndpointsAccountVerifyConfirmResponse> => {
  const res = await fetch(getAccountEndpointsAccountVerifyConfirmUrl(uidb64, token), {
    ...options,
    method: "PUT",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountEndpointsAccountVerifyConfirmResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountEndpointsAccountVerifyConfirmResponse;
};

/**
 * 注册账户, 如果用户已存在但未激活, 则更新用户信息
 * @summary 注册账户
 */
export type accountEndpointsRegisterResponse201 = {
  data: OutSchemaAccountOutSchema;
  status: 201;
};

export type accountEndpointsRegisterResponseSuccess = accountEndpointsRegisterResponse201 & {
  headers: Headers;
};
export type accountEndpointsRegisterResponse = accountEndpointsRegisterResponseSuccess;

export const getAccountEndpointsRegisterUrl = () => {
  return `/api/accounts`;
};

export const accountEndpointsRegister = async (registerInSchema: RegisterInSchema, options?: RequestInit): Promise<accountEndpointsRegisterResponse> => {
  const res = await fetch(getAccountEndpointsRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerInSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountEndpointsRegisterResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountEndpointsRegisterResponse;
};

/**
 * 获取书籍列表, 支持过滤和分页
 * @summary 获取书籍列表
 */
export type bookEndpointsGetBooksResponse200 = {
  data: OutSchemaListBookOutSchema;
  status: 200;
};

export type bookEndpointsGetBooksResponseSuccess = bookEndpointsGetBooksResponse200 & {
  headers: Headers;
};
export type bookEndpointsGetBooksResponse = bookEndpointsGetBooksResponseSuccess;

export const getBookEndpointsGetBooksUrl = (params?: BookEndpointsGetBooksParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/books?${stringifiedParams}` : `/api/books`;
};

export const bookEndpointsGetBooks = async (params?: BookEndpointsGetBooksParams, options?: RequestInit): Promise<bookEndpointsGetBooksResponse> => {
  const res = await fetch(getBookEndpointsGetBooksUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsGetBooksResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsGetBooksResponse;
};

/**
 * 创建书籍, 如果有封面则保存在媒体目录, 并且创建用户与书籍的作者关系
 * @summary 创建书籍
 */
export type bookEndpointsCreateBookResponse201 = {
  data: OutSchemaBookOutSchema;
  status: 201;
};

export type bookEndpointsCreateBookResponseSuccess = bookEndpointsCreateBookResponse201 & {
  headers: Headers;
};
export type bookEndpointsCreateBookResponse = bookEndpointsCreateBookResponseSuccess;

export const getBookEndpointsCreateBookUrl = () => {
  return `/api/books`;
};

export const bookEndpointsCreateBook = async (bookCreateInSchema: BookCreateInSchema, options?: RequestInit): Promise<bookEndpointsCreateBookResponse> => {
  const res = await fetch(getBookEndpointsCreateBookUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(bookCreateInSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsCreateBookResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsCreateBookResponse;
};

/**
 * 删除书籍接口, 要求用户必须是书籍的主创或管理员才能删除
 * @summary 删除书籍
 */
export type bookEndpointsDeleteBookResponse204 = {
  data: OutSchemaNoneType;
  status: 204;
};

export type bookEndpointsDeleteBookResponse403 = {
  data: OutSchemaNoneType;
  status: 403;
};

export type bookEndpointsDeleteBookResponse404 = {
  data: OutSchemaNoneType;
  status: 404;
};

export type bookEndpointsDeleteBookResponseSuccess = bookEndpointsDeleteBookResponse204 & {
  headers: Headers;
};
export type bookEndpointsDeleteBookResponseError = (bookEndpointsDeleteBookResponse403 | bookEndpointsDeleteBookResponse404) & {
  headers: Headers;
};

export type bookEndpointsDeleteBookResponse = bookEndpointsDeleteBookResponseSuccess | bookEndpointsDeleteBookResponseError;

export const getBookEndpointsDeleteBookUrl = (bookId: number) => {
  return `/api/books/${bookId}`;
};

export const bookEndpointsDeleteBook = async (bookId: number, options?: RequestInit): Promise<bookEndpointsDeleteBookResponse> => {
  const res = await fetch(getBookEndpointsDeleteBookUrl(bookId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsDeleteBookResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsDeleteBookResponse;
};

/**
 * 获取特定书籍
 * @summary 获取书籍
 */
export type bookEndpointsGetBookResponse200 = {
  data: OutSchemaBookOutSchema;
  status: 200;
};

export type bookEndpointsGetBookResponse403 = {
  data: OutSchemaNoneType;
  status: 403;
};

export type bookEndpointsGetBookResponse404 = {
  data: OutSchemaNoneType;
  status: 404;
};

export type bookEndpointsGetBookResponseSuccess = bookEndpointsGetBookResponse200 & {
  headers: Headers;
};
export type bookEndpointsGetBookResponseError = (bookEndpointsGetBookResponse403 | bookEndpointsGetBookResponse404) & {
  headers: Headers;
};

export type bookEndpointsGetBookResponse = bookEndpointsGetBookResponseSuccess | bookEndpointsGetBookResponseError;

export const getBookEndpointsGetBookUrl = (bookId: number) => {
  return `/api/books/${bookId}`;
};

export const bookEndpointsGetBook = async (bookId: number, options?: RequestInit): Promise<bookEndpointsGetBookResponse> => {
  const res = await fetch(getBookEndpointsGetBookUrl(bookId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsGetBookResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsGetBookResponse;
};

/**
 * 更新书籍
 * @summary 更新书籍
 */
export type bookEndpointsUpdateBookResponse200 = {
  data: OutSchemaBookOutSchema;
  status: 200;
};

export type bookEndpointsUpdateBookResponse403 = {
  data: OutSchemaNoneType;
  status: 403;
};

export type bookEndpointsUpdateBookResponse404 = {
  data: OutSchemaNoneType;
  status: 404;
};

export type bookEndpointsUpdateBookResponseSuccess = bookEndpointsUpdateBookResponse200 & {
  headers: Headers;
};
export type bookEndpointsUpdateBookResponseError = (bookEndpointsUpdateBookResponse403 | bookEndpointsUpdateBookResponse404) & {
  headers: Headers;
};

export type bookEndpointsUpdateBookResponse = bookEndpointsUpdateBookResponseSuccess | bookEndpointsUpdateBookResponseError;

export const getBookEndpointsUpdateBookUrl = (bookId: number) => {
  return `/api/books/${bookId}`;
};

export const bookEndpointsUpdateBook = async (bookId: number, bookUpdateInSchema: BookUpdateInSchema, options?: RequestInit): Promise<bookEndpointsUpdateBookResponse> => {
  const res = await fetch(getBookEndpointsUpdateBookUrl(bookId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(bookUpdateInSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsUpdateBookResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsUpdateBookResponse;
};

/**
 * 获取书籍的章节列表
 * @summary 获取章节列表
 */
export type bookEndpointsGetChaptersResponse200 = {
  data: OutSchemaListChapterOutSchema;
  status: 200;
};

export type bookEndpointsGetChaptersResponse403 = {
  data: OutSchemaNoneType;
  status: 403;
};

export type bookEndpointsGetChaptersResponse404 = {
  data: OutSchemaNoneType;
  status: 404;
};

export type bookEndpointsGetChaptersResponseSuccess = bookEndpointsGetChaptersResponse200 & {
  headers: Headers;
};
export type bookEndpointsGetChaptersResponseError = (bookEndpointsGetChaptersResponse403 | bookEndpointsGetChaptersResponse404) & {
  headers: Headers;
};

export type bookEndpointsGetChaptersResponse = bookEndpointsGetChaptersResponseSuccess | bookEndpointsGetChaptersResponseError;

export const getBookEndpointsGetChaptersUrl = (bookId: number, params?: BookEndpointsGetChaptersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/books/${bookId}/chapters?${stringifiedParams}` : `/api/books/${bookId}/chapters`;
};

export const bookEndpointsGetChapters = async (bookId: number, params?: BookEndpointsGetChaptersParams, options?: RequestInit): Promise<bookEndpointsGetChaptersResponse> => {
  const res = await fetch(getBookEndpointsGetChaptersUrl(bookId, params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsGetChaptersResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsGetChaptersResponse;
};

/**
 * 创建新章节
 * @summary 创建章节
 */
export type bookEndpointsCreateChapterResponse201 = {
  data: OutSchemaChapterOutSchema;
  status: 201;
};

export type bookEndpointsCreateChapterResponse403 = {
  data: OutSchemaNoneType;
  status: 403;
};

export type bookEndpointsCreateChapterResponse404 = {
  data: OutSchemaNoneType;
  status: 404;
};

export type bookEndpointsCreateChapterResponseSuccess = bookEndpointsCreateChapterResponse201 & {
  headers: Headers;
};
export type bookEndpointsCreateChapterResponseError = (bookEndpointsCreateChapterResponse403 | bookEndpointsCreateChapterResponse404) & {
  headers: Headers;
};

export type bookEndpointsCreateChapterResponse = bookEndpointsCreateChapterResponseSuccess | bookEndpointsCreateChapterResponseError;

export const getBookEndpointsCreateChapterUrl = (bookId: number) => {
  return `/api/books/${bookId}/chapters`;
};

export const bookEndpointsCreateChapter = async (bookId: number, chapterCreateInSchema: ChapterCreateInSchema, options?: RequestInit): Promise<bookEndpointsCreateChapterResponse> => {
  const res = await fetch(getBookEndpointsCreateChapterUrl(bookId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(chapterCreateInSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsCreateChapterResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsCreateChapterResponse;
};

/**
 * 删除章节
 * @summary 删除章节
 */
export type bookEndpointsDeleteChapterResponse204 = {
  data: OutSchemaNoneType;
  status: 204;
};

export type bookEndpointsDeleteChapterResponse403 = {
  data: OutSchemaNoneType;
  status: 403;
};

export type bookEndpointsDeleteChapterResponse404 = {
  data: OutSchemaNoneType;
  status: 404;
};

export type bookEndpointsDeleteChapterResponseSuccess = bookEndpointsDeleteChapterResponse204 & {
  headers: Headers;
};
export type bookEndpointsDeleteChapterResponseError = (bookEndpointsDeleteChapterResponse403 | bookEndpointsDeleteChapterResponse404) & {
  headers: Headers;
};

export type bookEndpointsDeleteChapterResponse = bookEndpointsDeleteChapterResponseSuccess | bookEndpointsDeleteChapterResponseError;

export const getBookEndpointsDeleteChapterUrl = (bookId: number, chapterNumber: number) => {
  return `/api/books/${bookId}/chapters/${chapterNumber}`;
};

export const bookEndpointsDeleteChapter = async (bookId: number, chapterNumber: number, options?: RequestInit): Promise<bookEndpointsDeleteChapterResponse> => {
  const res = await fetch(getBookEndpointsDeleteChapterUrl(bookId, chapterNumber), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsDeleteChapterResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsDeleteChapterResponse;
};

/**
 * 获取特定章节
 * @summary 获取章节
 */
export type bookEndpointsGetChapterResponse200 = {
  data: OutSchemaChapterOutSchema;
  status: 200;
};

export type bookEndpointsGetChapterResponse403 = {
  data: OutSchemaNoneType;
  status: 403;
};

export type bookEndpointsGetChapterResponse404 = {
  data: OutSchemaNoneType;
  status: 404;
};

export type bookEndpointsGetChapterResponseSuccess = bookEndpointsGetChapterResponse200 & {
  headers: Headers;
};
export type bookEndpointsGetChapterResponseError = (bookEndpointsGetChapterResponse403 | bookEndpointsGetChapterResponse404) & {
  headers: Headers;
};

export type bookEndpointsGetChapterResponse = bookEndpointsGetChapterResponseSuccess | bookEndpointsGetChapterResponseError;

export const getBookEndpointsGetChapterUrl = (bookId: number, chapterNumber: number) => {
  return `/api/books/${bookId}/chapters/${chapterNumber}`;
};

export const bookEndpointsGetChapter = async (bookId: number, chapterNumber: number, options?: RequestInit): Promise<bookEndpointsGetChapterResponse> => {
  const res = await fetch(getBookEndpointsGetChapterUrl(bookId, chapterNumber), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsGetChapterResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsGetChapterResponse;
};

/**
 * 更新章节信息
 * @summary 更新章节
 */
export type bookEndpointsUpdateChapterResponse200 = {
  data: OutSchemaChapterOutSchema;
  status: 200;
};

export type bookEndpointsUpdateChapterResponse403 = {
  data: OutSchemaNoneType;
  status: 403;
};

export type bookEndpointsUpdateChapterResponse404 = {
  data: OutSchemaNoneType;
  status: 404;
};

export type bookEndpointsUpdateChapterResponseSuccess = bookEndpointsUpdateChapterResponse200 & {
  headers: Headers;
};
export type bookEndpointsUpdateChapterResponseError = (bookEndpointsUpdateChapterResponse403 | bookEndpointsUpdateChapterResponse404) & {
  headers: Headers;
};

export type bookEndpointsUpdateChapterResponse = bookEndpointsUpdateChapterResponseSuccess | bookEndpointsUpdateChapterResponseError;

export const getBookEndpointsUpdateChapterUrl = (bookId: number, chapterNumber: number) => {
  return `/api/books/${bookId}/chapters/${chapterNumber}`;
};

export const bookEndpointsUpdateChapter = async (bookId: number, chapterNumber: number, chapterUpdateInSchema: ChapterUpdateInSchema, options?: RequestInit): Promise<bookEndpointsUpdateChapterResponse> => {
  const res = await fetch(getBookEndpointsUpdateChapterUrl(bookId, chapterNumber), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(chapterUpdateInSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsUpdateChapterResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsUpdateChapterResponse;
};

/**
 * 更新书籍封面
 * @summary 更新封面图片
 */
export type bookEndpointsUploadCoverImageResponse200 = {
  data: OutSchemaBookOutSchema;
  status: 200;
};

export type bookEndpointsUploadCoverImageResponse403 = {
  data: OutSchemaNoneType;
  status: 403;
};

export type bookEndpointsUploadCoverImageResponse404 = {
  data: OutSchemaNoneType;
  status: 404;
};

export type bookEndpointsUploadCoverImageResponseSuccess = bookEndpointsUploadCoverImageResponse200 & {
  headers: Headers;
};
export type bookEndpointsUploadCoverImageResponseError = (bookEndpointsUploadCoverImageResponse403 | bookEndpointsUploadCoverImageResponse404) & {
  headers: Headers;
};

export type bookEndpointsUploadCoverImageResponse = bookEndpointsUploadCoverImageResponseSuccess | bookEndpointsUploadCoverImageResponseError;

export const getBookEndpointsUploadCoverImageUrl = (bookId: number) => {
  return `/api/books/${bookId}/cover`;
};

export const bookEndpointsUploadCoverImage = async (bookId: number, bookEndpointsUploadCoverImageBody: BookEndpointsUploadCoverImageBody, options?: RequestInit): Promise<bookEndpointsUploadCoverImageResponse> => {
  const formData = new FormData();
  if (bookEndpointsUploadCoverImageBody.cover_image !== undefined) {
    formData.append(`cover_image`, bookEndpointsUploadCoverImageBody.cover_image);
  }

  const res = await fetch(getBookEndpointsUploadCoverImageUrl(bookId), {
    ...options,
    method: "PATCH",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookEndpointsUploadCoverImageResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as bookEndpointsUploadCoverImageResponse;
};

/**
 * 请求重置密码
 * @summary 请求重置密码
 */
export type accountEndpointsPasswordResetRequestResponse201 = {
  data: OutSchemaStr;
  status: 201;
};

export type accountEndpointsPasswordResetRequestResponseSuccess = accountEndpointsPasswordResetRequestResponse201 & {
  headers: Headers;
};
export type accountEndpointsPasswordResetRequestResponse = accountEndpointsPasswordResetRequestResponseSuccess;

export const getAccountEndpointsPasswordResetRequestUrl = () => {
  return `/api/password-resets`;
};

export const accountEndpointsPasswordResetRequest = async (emailRequestInSchema: EmailRequestInSchema, options?: RequestInit): Promise<accountEndpointsPasswordResetRequestResponse> => {
  const res = await fetch(getAccountEndpointsPasswordResetRequestUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(emailRequestInSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountEndpointsPasswordResetRequestResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountEndpointsPasswordResetRequestResponse;
};

/**
 * 使用令牌重置密码
 * @summary 使用令牌重置密码
 */
export type accountEndpointsPasswordResetConfirmResponse200 = {
  data: OutSchemaStr;
  status: 200;
};

export type accountEndpointsPasswordResetConfirmResponseSuccess = accountEndpointsPasswordResetConfirmResponse200 & {
  headers: Headers;
};
export type accountEndpointsPasswordResetConfirmResponse = accountEndpointsPasswordResetConfirmResponseSuccess;

export const getAccountEndpointsPasswordResetConfirmUrl = (uidb64: string, token: string) => {
  return `/api/password-resets/${uidb64}/${token}`;
};

export const accountEndpointsPasswordResetConfirm = async (uidb64: string, token: string, passwordResetConfirmInSchema: PasswordResetConfirmInSchema, options?: RequestInit): Promise<accountEndpointsPasswordResetConfirmResponse> => {
  const res = await fetch(getAccountEndpointsPasswordResetConfirmUrl(uidb64, token), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(passwordResetConfirmInSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountEndpointsPasswordResetConfirmResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountEndpointsPasswordResetConfirmResponse;
};

/**
 * 登录账户
 * @summary 登录账户
 */
export type accountEndpointsLoginResponse201 = {
  data: OutSchemaJwtOutSchema;
  status: 201;
};

export type accountEndpointsLoginResponseSuccess = accountEndpointsLoginResponse201 & {
  headers: Headers;
};
export type accountEndpointsLoginResponse = accountEndpointsLoginResponseSuccess;

export const getAccountEndpointsLoginUrl = () => {
  return `/api/sessions`;
};

export const accountEndpointsLogin = async (loginInSchema: LoginInSchema, options?: RequestInit): Promise<accountEndpointsLoginResponse> => {
  const res = await fetch(getAccountEndpointsLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginInSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountEndpointsLoginResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountEndpointsLoginResponse;
};

/**
 * 用于连通测试和基础状态检查，返回服务基本状态信息。
 * @summary 获取服务状态信息
 */
export type coreEndpointsGetStatusResponse200 = {
  data: OutSchemaStr;
  status: 200;
};

export type coreEndpointsGetStatusResponseSuccess = coreEndpointsGetStatusResponse200 & {
  headers: Headers;
};
export type coreEndpointsGetStatusResponse = coreEndpointsGetStatusResponseSuccess;

export const getCoreEndpointsGetStatusUrl = () => {
  return `/api/status`;
};

export const coreEndpointsGetStatus = async (options?: RequestInit): Promise<coreEndpointsGetStatusResponse> => {
  const res = await fetch(getCoreEndpointsGetStatusUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: coreEndpointsGetStatusResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as coreEndpointsGetStatusResponse;
};
