/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * NinjaExtraAPI
 * OpenAPI spec version: 1.0.0
 */
/**
 * 错误字段
 */
export type ErrorDetailSchemaField = string | null;

/**
 * 错误详情
 */
export interface ErrorDetailSchema {
  /** 错误字段 */
  field?: ErrorDetailSchemaField;
  /** 错误信息 */
  message: string;
}

/**
 * 响应数据
 */
export type OutSchemaStrData = string | null;

/**
 * 错误详情
 */
export type OutSchemaStrErrors = ErrorDetailSchema[] | null;

export interface OutSchemaStr {
  /** 响应数据 */
  data?: OutSchemaStrData;
  /** 错误详情 */
  errors?: OutSchemaStrErrors;
  /** 消息 */
  message?: string;
  /** 时间戳 */
  timestamp?: string;
}

/**
 * 用于连通测试和基础状态检查，返回服务基本状态信息。
 * @summary 获取服务状态信息
 */
export type coreEndpointsGetStatusResponse200 = {
  data: OutSchemaStr;
  status: 200;
};

export type coreEndpointsGetStatusResponseSuccess = coreEndpointsGetStatusResponse200 & {
  headers: Headers;
};
export type coreEndpointsGetStatusResponse = coreEndpointsGetStatusResponseSuccess;

export const getCoreEndpointsGetStatusUrl = () => {
  return `/api/status`;
};

export const coreEndpointsGetStatus = async (options?: RequestInit): Promise<coreEndpointsGetStatusResponse> => {
  const res = await fetch(getCoreEndpointsGetStatusUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: coreEndpointsGetStatusResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as coreEndpointsGetStatusResponse;
};
